#!/bin/bash

mkdir /tmp/rathole
cd /tmp/rathole
wget https://github.com/rapiz1/rathole/releases/latest/download/rathole-x86_64-unknown-linux-gnu.zip
unzip rathole-x86_64-unknown-linux-gnu.zip

cat > ratholec@.service <<EOF
[Unit]
Description=Rathole Client Service
After=network.target

[Service]
Type=simple
DynamicUser=yes
Restart=on-failure
RestartSec=3s
ExecStart=/usr/local/bin/rathole -c /etc/rathole/client/%i.toml

[Install]
WantedBy=multi-user.target
EOF

cat > rathole@.service <<EOF
[Unit]
Description=Rathole Service
After=network.target

[Service]
Type=simple
DynamicUser=yes
Restart=on-failure
RestartSec=3s
ExecStart=/usr/local/bin/rathole /etc/rathole/server/%i.toml

[Install]
WantedBy=multi-user.target
EOF

sudo mv rathole /usr/local/bin
sudo mv ratholec@.service /etc/systemd/system/
sudo mv rathole@.service /etc/systemd/system/
sudo systemctl daemon-reload

rm -r /tmp/rathole

# TODO Check if target files exists

echo "Rathole binaries and systemd services installed."
